# Site settings
title: Tharindu Ishan
description: Embedded Systems Engineer | B.Sc(Hons)Eng | AM(IESL) | AEng(ECSL) | DevOps | ML | AI Enthusiast
url: "https://your-username.github.io"
baseurl: ""

# Personal info
author:
  name: Tharindu Ishan
  email: wtiwijesinghe@gmail.com
  phone: "+9471-4367-160"
  location: "Colombo, Sri Lanka"
  linkedin: "tharindu-wijesinghe"
  github: "your-github-username"

# Theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# Navigation
navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects
  - title: About
    url: /about
  - title: Contact
    url: /#contact

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "project"
